config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'searches/index'
  end
  namespace :public do
    get 'searches/index'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :comments, only: [:destroy]
  end

  namespace :admin do
    resources :recipes, only: [:show]
  end

  namespace :admin do
    root to: 'homes#top'
  end
  
  namespace :admin do
    resources :searches, only: [:index]
  end
  
  scope module: :public do
    resources :bookmarks, only: [:index, :create, :destroy]
  end

  scope module: :public do
    resources :comments, only: [:create]
  end

  scope module: :public do
    resources :tags, only: [:create, :destroy]
  end
  patch "/tags/update_all" => "public/tags#update_all", as: "tags_update_all"

  scope module: :public do
    resources :seasoning_items, only: [:create, :destroy]
  end
  patch "/seasoning_items/update_all" => "public/seasoning_items#update_all", as:"seasoning_items_update_all"

  scope module: :public do
    resources :seasonings, only: [:create, :destroy]
  end
  patch "/seasonings/update_all" => "public/seasonings#update_all", as:"seasonings_update_all"

  scope module: :public do
    resources :steps, only: [:create, :destroy]
  end
  patch "/steps/update_all" => "public/steps#update_all", as:"steps_update_all"

  scope module: :public do
    resources :materials, only: [:create, :destroy]
  end
  patch "/materials/update_all" => "public/materials#update_all", as:"materials_update_all"

  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
  end
  get "/customers/withdraw_check" => "public/customers#withdraw_check", as: "withdraw_check"
  patch "/customers/withdraw" => "public/customers#withdraw", as: "withdraw"

  scope module: :public do
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  root to: 'public/homes#top'
  
  scope module: :public do
    resources :searches, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'public/sessions#guest_sign_in', as: "customers_guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :comments
  has_many :bookmarks

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.email = "guest@example.com"
      customer.first_name = "ゲスト"
      customer.last_name = "ユーザー"
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image
  has_many :comments
  has_many :bookmarks
  has_many :materials, inverse_of: :recipe
  has_many :steps, inverse_of: :recipe
  has_many :seasonings, inverse_of: :recipe
  has_many :tags, inverse_of: :recipe
  belongs_to :customer

  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :seasonings, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seasoning.rb
class Seasoning < ApplicationRecord
  belongs_to :recipe
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recipe

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    @comment = Comment.find(params[:id])
    comment = @comment.recipe_id
    @comment.destroy
    redirect_to admin_recipe_path(comment)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @recipes = Recipe.all.order(created_at: :desc).page(params[:page]).per(8)
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  def show
     @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(recipe_id: @recipe).page(params[:page]).per(5)
  end
  
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def index
    if  params["q"]["title_or_tags_name_cont"] == ""
      @searches = []
    else
      @searches = @search.result(distinct: true).includes(:tags).page(params[:page]).per(5).order("created_at desc")
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  before_action :authenticate_admin!, if: :admin_url

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def set_search
    @search = Recipe.ransack(params[:q])
    @result = params[:q]&.values&.reject(&:blank?)
    @check = params[:q]
  end

  def admin_url
    request.fullpath.include?("/admin")
  end
  
  
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/recipes/show.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-10"><b style="font-size:30px;">レシピ詳細</b></div>
  </div>

  <div class="row justify-content-center" style="margin-top:20px;">
    <div class="col-md-4" style="padding-left:0px; ">
      <div style="font-size:30px; text-align: center;"><b><%= @recipe.title %></b></div>
      <div style="text-align: end; font-size:20px;"><b>by <%= @recipe.customer.first_name %> <%= @recipe.customer.last_name %></b></div>
    </div>
    <div class="col-md-7 d-flex align-items-end" style="padding-left:20px; margin-left:0px; font-size:23px; border-bottom-style: solid; border-color: #696969;"><b>材料リスト(<%= @recipe.quantity%>人分)</b></div>
    
  </div>

  <div class="row justify-content-center" style="margin-top:20px;">
    <div class="col-md-4" style="text-align: end;">
      <%= image_tag @recipe.image, size: "280x280" %>
      <div>
        <span style="padding-right:110px;"><i class="fas fa-tag fa-2x"></i><b style="font-size:25px;">タグ</b></span>
        <span>
          <%= link_to "ﾌﾞｯｸﾏｰｸ",bookmarks_path(recipe_id: @recipe.id),method: :post,class:"btn btn-warning text-light",style:"width:90px; height:35px;" %>
        </span>
      </div>

      <div class="pull-right" style="width:300px; font-size:20px; word-break: keep-all; text-align: left; margin-left:70px;">
        <% @recipe.tags.each do |tag|%>
          <%= tag.name %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4" style="padding-left:20px;">
      <% @recipe.materials.each do |material|%>
        <div style="font-size:23px;">
          <span style="display: inline-block; width: 210px; border-bottom-style: solid; border-color: #696969;"><%= material.name %></span>
          <span style="display: inline-block; width: 120px; border-bottom-style: solid; border-color: #696969;"><%= material.quantity %></span>
        </div>
      <% end %>
    </div>

    <div class="col-md-3" style="padding-left:20px;">
      <% @recipe.seasonings.each do |seasoning|%>
        <div style="font-size:23px;">
          <span style="display: inline-block; width: 120px; border-bottom-style: solid; border-color: #696969;"><%= seasoning.name %></span>
          <span style="display: inline-block; width: 120px; border-bottom-style: solid; border-color: #696969;"><%= seasoning.quantity %></span>
        </div>
      <% end %>
　   </div>
  </div>

  <div class="row justify-content-center" style="margin-top:20px;">
    <div class="col-md-5" style="font-size:27px;"><b>作り方</b></div>
    <div class="col-md-5" style="font-size:20px; padding-left:50px;"><b style="font-size:27px;">コメント</b><b style="margin-left:15px;"><%= @recipe.comments.count%>件</b><b style="padding-left:127px;">投稿者</b></div>
  </div>

  <div class="row justify-content-center" style="margin-top:20px; margin-left:80px;">
    <div class="col-md-5" style="font-size:20px;">
      <% @recipe.steps.each do |step|%>
        <div style="font-size:22px;">
          <span style="display: inline-block; width: 500px; text-align: left; margin-top:5px; border-bottom-style: solid; border-color: #696969;"><%= step.content %></span>
        </div>
      <% end %>
    </div>

    <div class="col-md-7" style="font-size:20px; padding-left:91px;">
      <% @comments.each do |comment|%>
      <div style="font-size:22px;">
        <span style="display: inline-block; width: 280px; text-align: left; margin-top:5px; border-bottom-style: solid; border-color: #696969;"><%= comment.content %></span>
        <span style="display: inline-block; width: 150px; margin-top:5px; font-size:20px; border-bottom-style: solid; border-color: #696969;"><%= comment.customer.first_name %><%= comment.customer.last_name %></span>
        <span><%= link_to "削除",admin_comment_path(comment),method: :delete,class:"btn btn-danger text-light",style:"width:60px; height:35px;" ,"data-confirm" => "本当に削除しますか？" %></span>
      </div>
      <% end %>
      <div style="margin-top:20px; margin-left:25%; font-size:25px;">
        <%= paginate @comments %>
      </div>

    </div>
  </div>

</div>

app/views/admin/searches/index.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-12 d-flex align-items-center">
      <b style="font-size:30px;">
        <% if @result == [] %>
           <h1 class="mt-3 text-center">検索結果がありません。</h1>
        <% elsif @searches.present? %>
          <% search_word = @search.title_or_tags_name_cont %>
          <h1 class="mt-3">検索結果 "<%= search_word %>"</h1>
        <% end %>
      </b>
    </div>
  </div>

  <div class="row justify-content-center">
    <% @searches.each do |search| %>
    <div class="card col-md-12" style="width: 600px; height:300px; margin-top:10px;">
      <div class="row g-0">
        <div class="col-md-5" style="padding-left:0px;">
          <%= link_to admin_recipe_path(search.id) do %>
            <%= image_tag search.image, width: "450", height: "300", class:"card-img-top;" %>
          <% end %>
        </div>
        <div class="col-md-5">
          <div class="card-body">
            <h5 class="card-title" style="font-size:35px;"><strong><span><%= search.title %></span></strong></h5>
            <span style="font-size:1.5em;"><i class="fas fa-user"></i> By <%= search.customer.first_name %><%= search.customer.last_name %> </span></br>
            <span style="font-size:1.5em;"><%= search.comments.count %>コメント</span>
            <span style="font-size:1.5em;"><%= search.bookmarks.count %>ブックマーク</span>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div style="margin-top:50px; margin-left:42%; font-size:25px;">
    <% if @searches != []%>
      <%= paginate  @searches %>
    <%end%>
  </div>
</div>