config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'searches/index'
  end
  namespace :public do
    get 'searches/index'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :comments, only: [:destroy]
  end

  namespace :admin do
    resources :recipes, only: [:show]
  end

  namespace :admin do
    root to: 'homes#top'
  end
  
  namespace :admin do
    resources :searches, only: [:index]
  end
  
  scope module: :public do
    resources :bookmarks, only: [:index, :create, :destroy]
  end

  scope module: :public do
    resources :comments, only: [:create]
  end

  scope module: :public do
    resources :tags, only: [:create, :destroy]
  end
  patch "/tags/update_all" => "public/tags#update_all", as: "tags_update_all"

  scope module: :public do
    resources :seasoning_items, only: [:create, :destroy]
  end
  patch "/seasoning_items/update_all" => "public/seasoning_items#update_all", as:"seasoning_items_update_all"

  scope module: :public do
    resources :seasonings, only: [:create, :destroy]
  end
  patch "/seasonings/update_all" => "public/seasonings#update_all", as:"seasonings_update_all"

  scope module: :public do
    resources :steps, only: [:create, :destroy]
  end
  patch "/steps/update_all" => "public/steps#update_all", as:"steps_update_all"

  scope module: :public do
    resources :materials, only: [:create, :destroy]
  end
  patch "/materials/update_all" => "public/materials#update_all", as:"materials_update_all"

  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
  end
  get "/customers/withdraw_check" => "public/customers#withdraw_check", as: "withdraw_check"
  patch "/customers/withdraw" => "public/customers#withdraw", as: "withdraw"

  scope module: :public do
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  root to: 'public/homes#top'
  
  scope module: :public do
    resources :searches, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'public/sessions#guest_sign_in', as: "customers_guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :comments
  has_many :bookmarks

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.email = "guest@example.com"
      customer.first_name = "ゲスト"
      customer.last_name = "ユーザー"
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image
  has_many :comments
  has_many :bookmarks
  has_many :materials, inverse_of: :recipe
  has_many :steps, inverse_of: :recipe
  has_many :seasonings, inverse_of: :recipe
  has_many :tags, inverse_of: :recipe
  belongs_to :customer

  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :seasonings, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seasoning.rb
class Seasoning < ApplicationRecord
  belongs_to :recipe
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recipe

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    @comment = Comment.find(params[:id])
    comment = @comment.recipe_id
    @comment.destroy
    redirect_to admin_recipe_path(comment)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.order(created_at: :asc).page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @recipes = Recipe.where(customer_id: @customer).page(params[:page]).per(5)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @recipes = Recipe.all.order(created_at: :desc).page(params[:page]).per(8)
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  def show
     @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(recipe_id: @recipe).page(params[:page]).per(5)
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  before_action :authenticate_admin!, if: :admin_url

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def set_search
    @search = Recipe.ransack(params[:q])
    @result = params[:q]&.values&.reject(&:blank?)
    @check = params[:q]
  end

  def admin_url
    request.fullpath.include?("/admin")
  end
  
  
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-11 d-flex align-items-center"><strong style="font-size:30px;"><%= (@customer.first_name + @customer.last_name) %>さんの会員詳細</strong></div>
  </div>

  <%= form_with model: @customer, url:admin_customer_path(@customer), method: :patch  do |f|%>
  <div class="row justify-content-center" style="margin-top:30px; margin-left:30px; font-size:30px;">
    <div class="col-md-3" style="margin:auto 0;"><strong>会員ID</strong></div>
    <div class="col-md-6" style="padding-left:0px;"><strong><%= @customer.id %></strong></div>
  </div>

  <div class="row justify-content-center" style="margin-top:30px; margin-left:30px; font-size:30px;">
    <div class="col-md-3" style="margin:auto 0;"><strong>氏名</strong></div>
    <div class="col-md-6" style="padding-left:0px;"><strong><span><%= f.text_field :first_name,style:"width:190px; height:45px;"%></span><span style="margin-left:10px;"><%= f.text_field :last_name,style:"width:190px; height:45px;"%></span></strong></div>
  </div>

  <div class="row justify-content-center" style="margin-top:30px; margin-left:30px; font-size:30px;">
    <div class="col-md-3" style="margin:auto 0;"><strong>メールアドレス</strong></div>
    <div class="col-md-6" style="padding-left:0px;"><strong><%= f.email_field :email, autofocus: true, autocomplete: "email",style:"width:500px; height:45px;"%></strong></div>
  </div>

  <div class="row justify-content-center" style="margin-top:30px; margin-left:30px; font-size:30px;">
    <div class="col-md-3" style="margin:auto 0;"><strong>会員ステータス</strong></div>
    <div class="col-md-6" style="padding-left:0px; font-size:30px;">
      <strong>
        <%= f.radio_button :is_deleted, "false" %>
        <%= f.label :is_deleted, "有効",class:"mr-3" ,style:"color:#3cb371;" %>
        <%= f.radio_button :is_deleted, "true"%>
        <%= f.label :is_deleted, "退会" ,style:"color: #808080;" %>
      </strong>
    </div>
  </div>

  <div class="row justify-content-center" style="margin-top:30px;">
    <%= f.submit "変更を保存する",class:"btn btn-success text-center ",style:"width:190px; height:45px; font-size:20px;" %>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-11 d-flex align-items-center"><b style="font-size:30px;">会員一覧</b></div>
  </div>
  <div class="row justify-content-start" style="margin-top:35px;">
    <table class="table" style="font-size:28px;">
      <tr　class="border-top">
        <th bgcolor="#f5f5f5", style="width:10%" class="pl-3">会員ID</th>
        <th bgcolor="#f5f5f5", style="width:25%" class="pl-3">氏名</th>
        <th bgcolor="#f5f5f5", style="width:30%" class="pl-3">メールアドレス</th>
        <th bgcolor="#f5f5f5", style="width:15%" class="pl-3">ステータス</th>
      </tr>
    <% @customers.each do |customer| %>
      <% if customer.is_deleted ==true %>
      <tr class="border-bottom">
        <td><%= customer.id %></td>
        <td><%= link_to (customer.first_name + customer.last_name) , admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><strong style="color: #808080; margin-left:45px;">退会</strong></td>
      </tr>
      <% else%>
      <tr class="border-bottom">
        <td><%= customer.id %></td>
        <td><%= link_to (customer.first_name + customer.last_name) , admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><strong style="color:#3cb371; margin-left:45px;">有効</strong></td>
      </tr>
      <% end %>
    <% end %>
    </table>
  </div>
  <div style="margin-top:50px; margin-left:42%; font-size:25px;">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-11 d-flex align-items-center"><b style="font-size:30px;">会員詳細</b></div>
  </div>

  <div class="row" style="margin-top:10px;">
    <div class="col-md-6">
      <h3 class="row" style="margin-top:20px;">
        <strong class="col-md-5">会員ID</strong>
        <strong class="col-md-6" style="padding-left:20px;"><%= @customer.id %></strong>
      </h3>

      <h3 class="row" style="margin-top:20px;">
        <strong class="col-md-5">氏名</strong>
        <strong class="col-md-6"><%= @customer.first_name %><%= @customer.last_name %></strong>
      </h3>

      <h3 class="row" style="margin-top:20px;">
        <strong class="col-md-5">メールアドレス</strong>
        <strong class="col-md-6"><%= @customer.email %></strong>
      </h3>

       <h3 class="row" style="margin-top:20px;">
        <strong class="col-md-5">ステータス</strong>
        <% if @customer.is_deleted ==true %>
          <strong class="col-md-6" style="color: #808080;">無効</strong>
        <% else%>
          <strong class="col-md-6" style="color:#3cb371;">有効</strong>
        <% end %>
      </h3>

      <div class="row justify-content-center">
        <%= link_to "編集する", edit_admin_customer_path(@customer),class:"btn btn-success text-light mr-5 mt-4 ",style:"width:120px; height:45px; font-size:20px;" %>
      </div>
    </div>

    <div class="col-md-5">
      <table class="table" style="font-size:20px;">
        <tr　class="border-top">
          <th bgcolor="#f5f5f5", style="width:50%" class="pl-3">タイトル</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-1">コメント</th>
          <th bgcolor="#f5f5f5", style="width:25%" class="pl-1">ﾌﾞｯｸﾏｰｸ</th>
        </tr>
        <% @recipes.each do |recipe| %>
        <tr class="border-bottom">
          <td><%= link_to recipe.title ,admin_recipe_path(recipe) %></td>
          <td><%= recipe.comments.count %>件</td>
          <td><%= recipe.bookmarks.count %>件</td>
        </tr>
        <% end %>
      </table>

      <div style="margin-top:10px; margin-left:30%; font-size:20px;">
        <%= paginate @recipes %>
      </div>
    </div>
</div>














  </div>