config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'searches/index'
  end
  namespace :public do
    get 'searches/index'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :comments, only: [:destroy]
  end

  namespace :admin do
    resources :recipes, only: [:show]
  end

  namespace :admin do
    root to: 'homes#top'
  end
  
  namespace :admin do
    resources :searches, only: [:index]
  end
  
  scope module: :public do
    resources :bookmarks, only: [:index, :create, :destroy]
  end

  scope module: :public do
    resources :comments, only: [:create]
  end

  scope module: :public do
    resources :tags, only: [:create, :destroy]
  end
  patch "/tags/update_all" => "public/tags#update_all", as: "tags_update_all"

  scope module: :public do
    resources :seasoning_items, only: [:create, :destroy]
  end
  patch "/seasoning_items/update_all" => "public/seasoning_items#update_all", as:"seasoning_items_update_all"

  scope module: :public do
    resources :seasonings, only: [:create, :destroy]
  end
  patch "/seasonings/update_all" => "public/seasonings#update_all", as:"seasonings_update_all"

  scope module: :public do
    resources :steps, only: [:create, :destroy]
  end
  patch "/steps/update_all" => "public/steps#update_all", as:"steps_update_all"

  scope module: :public do
    resources :materials, only: [:create, :destroy]
  end
  patch "/materials/update_all" => "public/materials#update_all", as:"materials_update_all"

  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
  end
  get "/customers/withdraw_check" => "public/customers#withdraw_check", as: "withdraw_check"
  patch "/customers/withdraw" => "public/customers#withdraw", as: "withdraw"

  scope module: :public do
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  root to: 'public/homes#top'
  
  scope module: :public do
    resources :searches, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'public/sessions#guest_sign_in', as: "customers_guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :comments
  has_many :bookmarks

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.email = "guest@example.com"
      customer.first_name = "ゲスト"
      customer.last_name = "ユーザー"
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image
  has_many :comments
  has_many :bookmarks
  has_many :materials, inverse_of: :recipe
  has_many :steps, inverse_of: :recipe
  has_many :seasonings, inverse_of: :recipe
  has_many :tags, inverse_of: :recipe
  belongs_to :customer

  accepts_nested_attributes_for :materials, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :seasonings, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end
  
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seasoning.rb
class Seasoning < ApplicationRecord
  belongs_to :recipe
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recipe

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @recipes = Recipe.all.order(created_at: :desc).page(params[:page]).per(8)
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  def show
     @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(recipe_id: @recipe).page(params[:page]).per(5)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  before_action :authenticate_admin!, if: :admin_url

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def set_search
    @search = Recipe.ransack(params[:q])
    @result = params[:q]&.values&.reject(&:blank?)
    @check = params[:q]
  end

  def admin_url
    request.fullpath.include?("/admin")
  end
  
  
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0a8cfa57a2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# ヘッダー %>
    <nav class=" navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
      <div class="container-fluid">
        <% if admin_signed_in? %>
          <%= link_to admin_root_path ,class:"navbar-brand" do %>
            <%= image_tag 'image1.jpg', size: "200x200" %>
          <% end %>
        <% else %>
          <%= link_to root_path ,class:"navbar-brand" do %>
            <%= image_tag 'image1.jpg', size: "200x200" %>
          <% end %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to  customers_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">マイページ</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  recipes_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">レシピ一覧</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to bookmarks_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:200px; height:50px; font-size:20px; margin-right:20px;">ブックマーク一覧</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">ログアウト</button>
              <% end %>
            </li>

            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to  admin_customers_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">会員一覧</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  admin_root_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">レシピ一覧</button>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">ログアウト</button>
              <% end %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to  recipes_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:150px; height:50px; font-size:20px; margin-right:20px;">レシピ一覧</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:120px; height:50px; font-size:20px; margin-right:20px;">新規登録</button>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path, class:"nav-link" do %>
                <button  class="btn btn-outline-dark" style="width:120px; height:50px; font-size:20px; margin-right:20px;">ログイン</button>
              <% end %>
            </li>
            <% end %>
          </ul>

          <% if admin_signed_in?%>
          <ul class="list-unstyled" style="margin-top:10px;">
            <li class="mr-4">
              <%= search_form_for @search, url: admin_searches_path do |f| %>
              <div class="d-flex justify-content-end">
                <%= f.search_field :title_or_tags_name_cont, class: 'form-control mr-2', placeholder: '検索ワード', style:"border: 2px solid #000000; width: 400px; height:45px; font-size:20px;"%>
                <%= f.submit '検索', class: 'btn btn-primary text-light' ,style:"width:80px; height:45px; font-size:20px;" %>
              </div>
              <% end %>
            </li>
          </ul>
          <% else%>
          <ul class="list-unstyled" style="margin-top:10px;">
            <li class="mr-4">
              <%= search_form_for @search, url: searches_path do |f| %>
              <div class="d-flex justify-content-end">
                <%= f.search_field :title_or_tags_name_cont, class: 'form-control mr-2', placeholder: '検索ワード', style:"border: 2px solid #000000; width: 400px; height:45px; font-size:20px;"%>
                <%= f.submit '検索', class: 'btn btn-primary text-light' ,style:"width:80px; height:45px; font-size:20px;"%>
              </div>
              <% end %>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <%# 各view表示%>
    <div style="margin-top:10px;">
      <%= yield %>
    </div>

    <%# フッター %>
    <div class="mt-auto" style="padding-top:50px;">
      <P class="text-center" style="font-size:20px;">CopyRight Infratop.inc</P>
    </div>
  </body>
</html>